CREATE TABLE "BugTracker"."Users"
(
    ID SERIAL PRIMARY KEY UNIQUE,
    LOGIN VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128),
    POST VARCHAR(128)
);

CREATE TABLE "BugTracker"."Projects"
(
    ID SERIAL PRIMARY KEY UNIQUE,
    NAME VARCHAR(128) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(1024)
);

CREATE TABLE "BugTracker"."Issues"
(
    ID SERIAL PRIMARY KEY UNIQUE,
    "number" INTEGER NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(128),
	STATUS VARCHAR(128),
	PROJECT INTEGER,
	"user" INTEGER,
	FOREIGN KEY (PROJECT) REFERENCES "BugTracker"."Projects" (ID),
	FOREIGN KEY ("user") REFERENCES "BugTracker"."Users" (ID)
);

INSERT INTO "BugTracker"."Users" VALUES (DEFAULT, 'root', '0ca1c3339001f2fd522d9d5fc84448050675cb6853a2729fc7a466a68860e11a:c0da6ba75acd9df9')
